"""description of changes2

Revision ID: 6a6b99bc3d46
Revises: 3ad1f80ab3c6
Create Date: 2025-09-29 18:46:31.001197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6b99bc3d46'
down_revision: Union[str, None] = '3ad1f80ab3c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_attempts', 'flashcard_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_attempts', 'flashcard_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
