"""add membership time

Revision ID: 8196f0a3ae57
Revises: 9fcd7d20adda
Create Date: 2025-04-21 16:49:16.090554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8196f0a3ae57'
down_revision: Union[str, None] = '9fcd7d20adda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('start_member_date_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('end_member_date_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'end_member_date_time')
    op.drop_column('users', 'start_member_date_time')
    # ### end Alembic commands ###
