"""proper chapters

Revision ID: aa4e8ed47edd
Revises: f7dc698906c3
Create Date: 2025-07-02 01:32:44.236597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4e8ed47edd'
down_revision: Union[str, None] = 'f7dc698906c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('chapters', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('chapters', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chapters', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chapters', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.drop_column('chapters', 'user_id')
    op.drop_column('chapters', 'updated_at')
    op.drop_column('chapters', 'created_at')
    op.drop_column('chapters', 'order')
    # ### end Alembic commands ###
