name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, dev ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # test-backend:
  #   runs-on: ubuntu-latest
  #   services:
  #     postgres:
  #       image: postgres:14
  #       env:
  #         POSTGRES_USER: user
  #         POSTGRES_PASSWORD: password
  #         POSTGRES_DB: mydatabase
  #       ports:
  #         - 5432:5432
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Install Doppler CLI
  #       uses: dopplerhq/cli-action@v3
  #       with:
  #         doppler-token: ${{ secrets.DOPPLER_TOKEN_DEV }}

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.11'

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         cd backend
  #         pip install -r requirements.txt
  #         pip install pytest pytest-cov

  #     - name: Run tests
  #       run: |
  #         cd backend
  #         doppler run -- pytest --cov=app --cov-report=xml

  #     - name: Upload coverage report
  #       uses: codecov/codecov-action@v3
  #       with:
  #         file: ./backend/coverage.xml

  build-backend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN_DEV }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        run: |
          cd backend
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            # For tags, use the tag version
            VERSION=${GITHUB_REF#refs/tags/}
            doppler run -- docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:$VERSION .
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:$VERSION
          else
            # For branches, use branch name
            BRANCH=${GITHUB_REF#refs/heads/}
            doppler run -- docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:$BRANCH .
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:$BRANCH
          fi

  build-frontend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN_DEV }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend
        run: |
          cd frontend
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            # For tags, use the tag version
            VERSION=${GITHUB_REF#refs/tags/}
            doppler run -- docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:$VERSION .
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:$VERSION
          else
            # For branches, use branch name
            BRANCH=${GITHUB_REF#refs/heads/}
            doppler run -- docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:$BRANCH .
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:$BRANCH
          fi

  deploy:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN_PROD }}

      - name: Deploy to production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            export DOPPLER_TOKEN='${{ secrets.DOPPLER_TOKEN_PROD }}'
            export VERSION='${GITHUB_REF#refs/tags/}'
            echo "Start deploying version $VERSION"
            ./deploy.sh
